language: python
sudo: false
python:
  - 3.5
install: pip install -r dev-requirements.txt
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - nosetests web/test
  - ./acceptance/run
