#!/bin/bash
root_path=$(cd "$(dirname $BASH_SOURCE)/.."; pwd)

# Spawn web
pushd "${root_path}/web"
python server.py &
web_pid=$!
popd
echo "[INFO] Web PID: ${web_pid}."
sleep 1

# Run Behave tests
behave "${root_path}/acceptance"
behave_exit_code=$?

# Kill the arsehole
echo "[INFO] Killing web..."
kill "${web_pid}"
echo "[INFO] All microservices are gone (hopefully)."

exit "${behave_exit_code}"

